### PR TITLE
Add docker-compose.yml

### PR DESCRIPTION
**Pull request by sirikid**

### CODE REVIEW

**Comment by jrogov** [comment]
A few notes:
- Might be good to lower docker compose version (just 3?): not everyone might use the latest version, and also there's no need for recently added features
- `restart: always`?
- Should we test some `Replicated*Tree` Engines as well? In this case, zookeeper is also needed. 
  - But it will be more important for `clickhouse_ecto`: e.g. migrations for `Replicated*Tree`

**Comment by sirikid** [comment]
> Might be good to lower docker compose version (just 3?): not everyone might use the latest version, and also there's no need for recently added features

Didn't think about it. Done.

> restart: always?

Added.

> Should we test some Replicated*Tree Engines as well? In this case, zookeeper is also needed. 

Let's add zookeeper with the tests. I am not gonna do them now.

**Comment by jrogov** [comment]
>Let's add zookeeper with the tests. I am not gonna do them now.

You mean to postpone it till necessary?

**Comment by sirikid** [comment]
> You mean to postpone it till necessary?

Yep.

**Comment by jrogov** [comment]
This will do.

LGTM

**Pull request merged**
