### PR TITLE
Changed http client to mint

### PR DESCRIPTION
**Pull request by scohen**
The mint people were kind enough to make a synchronous data handling feature for me, I switched the HTTP library to use mint rather than HTTPoison.

This has the following benefits:

  * Many fewer dependencies
  * Much simpler supervision tree
  * We get a message whenever the server sends us data, which allows us
    to parse data as it comes in rather than all at once. This saves us
    buffer allocations and improves performance
  * There are no additional processes created, so it works much better
    with DBConnection. Now a connection is a single process instead of
    being a front for many processes. This should improve resillience.

### CODE REVIEW

**Comment by scohen** [comment]
@santaux Ping!

**Comment by santaux** [comment]
@scohen Hi man! I'm sorry for a such huge delay. Please, resolve the conflicts and I'll merge it to the master.

**Comment by scohen** [comment]
@santaux It figures that when you get back to me, that I'll be on vacation ;)
I rebased and resolved the conflicts, but I haven't been able to run it locally, and I've lost all context here.. Do you have CI set up? I'd hate to have this break something.

**Comment by santaux** [comment]
@scohen I understand, sorry for that... I don't have CI set up here but I'll do something with that, thank you :)

**Pull request merged**
